# Generated by Django 5.0 on 2024-02-22 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_borrowhistory_posted_on"),
        ("book", "0004_alter_review_posted_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowhistory",
            name="book",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="book.book"
            ),
        ),
    ]
