# Generated by Django 5.0 on 2024-02-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="posted_on",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
